#!/usr/bin/env node
"use strict";

const cluster = require("cluster");
const pkg = require("./package.json");
const { createSimulator } = require("./src/main");

function resolveModelPath(p) {
  let ret = require("path").join( __dirname, 'models', p);
  console.log("p:" , p , "ret:" , ret);
  return ret
}

if (cluster.isMaster) {
  const program = require("commander")
    .version(pkg.version)
    .description(pkg.description)
    .option("-u, --acs-url [url]", "ACS URL to contact (default: http://127.0.0.1:57547/)", "http://127.0.0.1:57547/")
    .option("-m, --data-model [filename]", "Data model template", resolveModelPath, "./models/data_model_202BC1-BM632w-8KA8WA1151100043.csv")
    .option("-p, --processes [count]", "Number of devices to simulate (default: 1)", parseFloat, 1)
    .option("-w, --wait [milliseconds]", "Waiting period between process spawning (default: 1000)", parseFloat, 1000)
    .option("-s, --serial [offset]", "Base serial number (default: 0)", parseFloat, 0)
    .parse(process.argv);

  program.parse()


  if (!/^(http|https):\/\//.test(program.opts().acsUrl)) {
    console.error(`Invalid ACS URL: "${program.opts().acsUrl}"`);
    process.exit(1);
  }
  for (
    let baseMac = 281474959933440, i = 0;
    i < program.opts().processes;
    baseMac++, i++
  ) {
    setTimeout(function() {
      var usedMac = baseMac.toString(16).toUpperCase().slice(-12).match(/../g).join(':');
      let env = {
        "MAC_ADDR": usedMac,
        "SERIAL_NUMBER": `00000${program.opts().serial + i}`.slice(-6),
        "ACS_URL": program.opts().acsUrl,
        "DATA_MODEL": program.opts().dataModel,
      };
      let worker = cluster.fork(env);
      worker.env = env;
    }, 1000 + i  * program.opts().wait)
  }
  cluster.on("fork", function(worker) {
    console.log(`Simulator ${worker.env["SERIAL_NUMBER"]} started`);
  });
  cluster.on("exit", function(worker, code, signal) {
    console.log(`Simulator ${worker.env["SERIAL_NUMBER"]} died (${signal || code}). Restarting in 10 seconds...`)
    setTimeout(function() {
      let newWorker = cluster.fork(worker.env);
      newWorker.env = worker.env;
    }, 10000);
  });
} else {
  const acsUrl = process.env["ACS_URL"];
  const dataModel = process.env["DATA_MODEL"];
  const serialNumber = process.env["SERIAL_NUMBER"];
  const macAddr = process.env["MAC_ADDR"];

  let simulator = createSimulator(acsUrl, dataModel, serialNumber, macAddr, true)
  .on('error', (e) => { // connection or task name errors during cwmp communication.
    console.error(e);
    process.exit(1);
  });
  return simulator.start().catch((e) => { // initialization error.
    console.error(e);
    process.exit(1);
  });
}